language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script: composer install -q

script:
  - phpunit
  - vendor/bin/phpspec run

notifications:
  email:
    recipients:
      - contact@djlechuck.fr
