language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script: composer install

script: phpunit --bootstrap vendor/autoload.php --colors tests

notifications:
  email:
    recipients:
      - contact@djlechuck.fr
